apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-database
spec:
  provider: vault
  secretObjects:
    - data:
        - key: POSTGRES_PASSWORD
          objectName: pg_credentials
        - key: REDIS_PASSWORD
          objectName: redis_password
        - key: REDISCLI_AUTH
          objectName: rediscli_auth
      secretName: dbpass
      type: Opaque
  parameters:
    vaultAddress: "http://vault.default:8200"
    roleName: "database"
    objects: |
      - objectName: "pg_credentials"
        secretPath: "secret/pg_credentials"
        secretKey: "POSTGRES_PASSWORD"
      - objectName: "redis_password"
        secretPath: "secret/redis_credentials"
        secretKey: "REDIS_PASSWORD"
      - objectName: "rediscli_auth"
        secretPath: "secret/redis_credentials"
        secretKey: "REDISCLI_AUTH"
