apiVersion: v1
kind: ConfigMap
metadata:
  name: conf
data:
 nginx_conf: |
    server {
        listen       80;
        server_name  localhost;
    
        #charset koi8-r;
        #access_log  /var/log/nginx/host.access.log  main;
    
        location / {
            return 301 https://$host$request_uri;
            deny all;
        }
        location /nginx_status {
        stub_status;
        #allow 127.0.0.1;	#only allow requests from localhost
        #deny all;		#deny all other hosts	
        }
    
        location /metrics {
        stub_status;
        }
    }

    server {
        listen       443 ssl;
        ssl_certificate /etc/nginx/ssl.crt;
        ssl_certificate_key /etc/nginx/ssl.key;
        #charset koi8-r;
        #access_log  /var/log/nginx/host.access.log  main;
    
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
        location /nginx_status {
        stub_status;
        allow 127.0.0.1;	#only allow requests from localhost
        deny all;		#deny all other hosts	
        }
    
        location /metrics {
        stub_status;
        }
        #error_page  404              /404.html;
        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
  
    }
 ssl_crt: |
    -----BEGIN CERTIFICATE-----
    MIICpDCCAYwCCQCpswXt4Qu0PzANBgkqhkiG9w0BAQsFADAUMRIwEAYDVQQDDAls
    b2NhbGhvc3QwHhcNMjMwNTEzMTMyOTI5WhcNMzMwNTEwMTMyOTI5WjAUMRIwEAYD
    VQQDDAlsb2NhbGhvc3QwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDh
    Nbv/NQSAKARlM573vPNXjk6oy5zeghH+3Y8JU9Ng4agjDoPUfAaPJnCrxvJS6DrW
    8qNv6I79EqWkAG9Qn7KTe3E9q+C0LEvBqWTYHLsRBKCEdNu0QllxwcUtqEUEtrtf
    BD96EeYcWyzHXgfXNhWYMAVepkGxd4C2W4raC7i+3aR1EtoR2fiep5vqMVCrFw7j
    kP0UzkaCa3PMUOU7gvX4zVAkQkKREf6JzwVBs4mk8Ki608JGULFZ2eFyeY3AIASO
    UpqlqyabYk/7mBdbBEeG6SxVpvVfyqLkDikQkNVPwaRXnk6KX8pmTVpVbw6gC862
    JYSUs6KVrfk9HJzc2uR5AgMBAAEwDQYJKoZIhvcNAQELBQADggEBAD85YrHzm+f9
    t/uHy14JOwfZPdtpRL0dKP76TcFx5U5KHNsOuXY2LLZ7Tqz1WeWu4POQJM7c3K1U
    9hsUtlsX3/x+DomIRGVvr9Oa5gXu3RDKzsIC6NX2pGv43YD7aTnSVlhnAmh2m50B
    9VFlpexwFnMZqc21QgdDdbUklkp3VsiSrCsV03sGrr7Kyk4xxByRuOsguMwiWXEi
    DnPHsYJEqsR/rS9EurYm3lUCpBzZpiKdC0+teTVgAk9fPhcZ1fkkiD59QEn7SS7y
    kulrI6JfiiF+zcJyPBAcOXGLeMKZ9cE9mGOeDEb78aIU9BNY9XAOVHn9H5LcNi8a
    Y73Km9GRvPI=
    -----END CERTIFICATE-----
 ssl_key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDhNbv/NQSAKARl
    M573vPNXjk6oy5zeghH+3Y8JU9Ng4agjDoPUfAaPJnCrxvJS6DrW8qNv6I79EqWk
    AG9Qn7KTe3E9q+C0LEvBqWTYHLsRBKCEdNu0QllxwcUtqEUEtrtfBD96EeYcWyzH
    XgfXNhWYMAVepkGxd4C2W4raC7i+3aR1EtoR2fiep5vqMVCrFw7jkP0UzkaCa3PM
    UOU7gvX4zVAkQkKREf6JzwVBs4mk8Ki608JGULFZ2eFyeY3AIASOUpqlqyabYk/7
    mBdbBEeG6SxVpvVfyqLkDikQkNVPwaRXnk6KX8pmTVpVbw6gC862JYSUs6KVrfk9
    HJzc2uR5AgMBAAECggEAfjKSKiwXXYkPDXajuccTxRhlU4jlWnogg2S75komxL8u
    bJaRoNvvAQBVWqyc1YB0mEZW9zqmBYIRd5kWx2L1ulcN2bUasVuxB9BYRhGzcZHa
    MN8aziPv4yLlzvPf2Qhcbp3+w/SLsZAVw5IZaqtP5nviRmt7nGqOoaEiaZTv7WNQ
    c3foU7SuZz4jyqIBNUG8gmUOLTHvZiYbsvTlgZDk4i8DdDaPZ/y7ciM2eimAv4zZ
    9Q5AqEzNjK+sNA07bBY0Cs9UsmXkzM4bBjzlIIN+1h0YTypgzcuNGnKkyomsa7RW
    UA73o4cR5a+ecBWLwULxEssvtN7d3IpZRYuzoZmikQKBgQD8z+QfMKqZtgfhsUeR
    fZ0ZYBfvpfqVQere7In5Y4+F0wK7WO0AdsR/IGe7SNyVbIvtVScRoyv4sbmcfCnb
    dfVfFiWLTRQEyFmpQ1w0rD8jDohKqzW0mGhDbWXFwuTaq1FtEgS9EZtwMb7/tl19
    YR8T5dakMUyijlMkK5Qr9C0uvwKBgQDkDL1wp+7OKkIg8LzTyfBlhXg2RE21CyZ5
    /KHqmXmKnZuyhg5TJlj2O2B7JjTfsMi2XWRDn0kKdQG7BgcXTZW/JKs1iN3oDvaj
    u9TcF6Lgweh9pS54y8JwmRiKlVDOhVCcEY9dbGVJeEZip2fsmdzKuSKNS2eJ6ul4
    +C4P1jXyxwKBgQCaR1vVVOOnbhidOIyOUvPeGnBBBS9IirOEWyFQGdvqNP1Dy17G
    m7QKSIJFHo/OeDFkIkT3VHZvDDZTMspwbSnSXzeGLQF8ca+Vxc+tLThScnnl51mc
    3i0yiL5E00zJzSahww81Olt7OkBu2KFw9CX9BJPaG2PDB8vhFN8Ve6tfDQKBgQC5
    J8bfotl3NkQ+rncBlaHDK5ywosBcz9LLlFx6N2XBL7nsNn+G70mnkgoBssGXJNex
    iR4Q8VDCVsGy8W/scae1a7Y+XwOcmBmUUrq+f8pUpdt3uBeFKBqUhRix3A2hwAf0
    zyUReyK5hhfPnY/5P+tOBQaSpbhI+BvbhdUQMqHWnQKBgQCVvlEXVCpP3qGT6hcG
    ZOw6MJnIdVWgExgwjhJxrjUIe99EYbSzmteh5P+GYNUF/vcjxm25qUCgYGp1BwUD
    zfLLISp2XiRJou0lGiDOtvMSjj8H8gEpdPZ5RXXfpYqEcqxBDmz/KoJEMBHYINW2
    4h6YdWyugA+WZ69/wwf/IH3kdw==
    -----END PRIVATE KEY-----

