{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.pgdata.claimName }}
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.volume.pgdata.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
{{- end }}