apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcName }}
spec:
  storageClassName: {{ .Values.pvcClassName }}
  resources:
    requests:
      storage: {{ .Values.pvcSize }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
